let stateAbbrev = {
    'Alabama' : 'AL',
    'Alaska' : 'AK',
    'America Samoa' : 'AS',
    'Arizona' : 'AZ',
    'Arkansas' : 'AR',
    'California' : 'CA',
    'Colorado' : 'CO',
    'Connecticut' : 'CT',
    'Delaware' : 'DE',
    'District of Columbia' : 'DC',
    'Federated States of Micronesia' : 'FM',
    'Florida' : 'FL',
    'Georgia' : 'GA',
    'Guam' : 'GU',
    'Hawaii' : 'HI',
    'Idaho' : 'ID',
    'Illinois' : 'IL',
    'Indiana' : 'IN',
    'Iowa' : 'IA',
    'Kansas' : 'KS',
    'Kentucky' : 'KY',
    'Louisiana' : 'LA',
    'Maine' : 'ME',
    'Maryland' : 'MD',
    'Massachusetts' : 'MA',
    'Marshall Islands' : 'MH',
    'Michigan' : 'MI',
    'Minnesota' : 'MN',
    'Mississippi' : 'MS',
    'Missouri' : 'MO',
    'Montana' : 'MT',
    'Nebraska' : 'NE',
    'Nevada' : 'NV',
    'New Hampshire' : 'NH',
    'New Jersey' : 'NJ',
    'New Mexico' : 'NM',
    'New York' : 'NY',
    'North Carolina' : 'NC',
    'North Dakota' : 'ND',
    'Northern Mariana Islands' : 'MP',
    'Ohio' : 'OH',
    'Oklahoma' : 'OK',
    'Oregon' : 'OR',
    'Palau' : 'PW',
    'Pennsylvania' : 'PA',
    'Puerto Rico' : 'PR',
    'Rhode Island' : 'RI',
    'South Carolina' : 'SC',
    'South Dakota' : 'SD',
    'Tennessee' : 'TN',
    'Texas' : 'TX',
    'Utah' : 'UT',
    'Vermont' : 'VT',
    'Virgin Island' : 'VI',
    'Virginia' : 'VA',
    'Washington' : 'WA',
    'West Virginia' : 'WV',
    'Wisconsin' : 'WI',
    'Wyoming' : 'WY'
  };

let abbrevAdjust = {
  "New Jersey": {x: 10, y: 5},
  "Hawaii": {x: -8, y: 0},
  "Louisiana": {x: -5, y: 0},
  "Michigan": {x: 3, y: 8},
  "Florida": {x: 5, y: 0},
  "Delaware": {x: 8, y: 4, fontSize: '4px'},
  "Connecticut": {x: 0, y: 1, fontSize: '4px'},
  "Rhode Island": {x: 3, y: 6, fontSize: '4px'},
  "Massachusetts": {x: 0, y: 0.5, fontSize: '4px'},
  "Vermont": {x: -0.5, y: 0, fontSize: '5px'},
  "New Hampshire": {x: 0, y: 5, fontSize: '4px'},
  "District of Columbia": {x: 2, y: 0, fontSize: '1px'},
  "Maryland": {x: -2, y: -1, fontSize: '4px'},
  "Kentucky": {x: 0, y: 3},
  "Tennessee": {x: 0, y: 2},
  "California": {x: -4, y: 0}
};

let stateElectoralVotes = {
  "Indiana": 11,
  "Kentucky": 8,
  "Vermont": 3,
  "West Virginia": 5,
  "Oklahoma": 7,
  "Delaware": 3,
  "Maryland": 10,
  "Massachusetts": 11,
  "New Jersey": 14,
  "District of Columbia": 3,
  "South Carolina": 9,
  "Tennessee": 11,
  "Alabama": 9,
  "Rhode Island": 4,
  "Mississippi": 6,
  "Illinois": 20,
  "Kansas": 6,
  "North Dakota": 3,
  "South Dakota": 3,
  "Texas": 38,
  "Wyoming": 3,
  "New York": 29,
  "Nebraska": 5,
  "Arkansas": 6,
  "Connecticut": 7,
  "Louisiana": 8,
  "Montana": 3,
  "New Mexico": 5,
  "Missouri": 10,
  "Ohio": 18,
  "Virginia": 13,
  "Colorado": 9,
  "Florida": 29,
  "Idaho": 4,
  "California": 55,
  "Hawaii": 4,
  "Oregon": 7,
  "North Carolina": 15,
  "Washington": 12,
  "Georgia": 16,
  "Utah": 6,
  "Iowa": 6,
  "Nevada": 6,
  "Pennsylvania": 20,
  "Maine": 4,
  "Wisconsin": 10,
  "Minnesota": 10,
  "Alaska": 3,
  "Arizona": 11,
  "New Hampshire": 4,
  "Michigan": 16
};
